projects:
  chatbot:
    schemaPath: lib/chatbot-api/schema/schema.graphql
    includes:
      - lib/user-interface/react-app/src/queries.ts
      - lib/user-interface/react-app/src/mutations.ts
      - lib/user-interface/react-app/src/subscriptions.ts
    excludes:
      - ./amplify/**
    extensions:
      amplify:
        codeGenTarget: typescript
        generatedFileName: lib/user-interface/react-app/src/API.ts
        region: us-east-1
        apiId: null
        frontend: javascript
        framework: react
        maxDepth: 2
extensions:
  amplify:
    version: 3
